### ISSUE TITLE
Enhance the demo

### ISSUE THREAD

**Issue by amitguptagwl** [amitguptagwl/shabdawali#11]
Provide the buttons to set repeat flag, add text content etc (index.html)

**Comment by inikonorov** [comment]
hello :) can I do audio effect point?

**Comment by amitguptagwl** [comment]
@inikonorov yes please.


> [Bookmark](https://github.com/amitguptagwl/shabdawali/stargazers) this project.
> join [Team](https://github.com/socialat/team/issues) to support opensource community.

**Comment by inikonorov** [comment]
hi again :) can I take UI design point?

**Comment by inikonorov** [comment]
hi, button for repeat should be button or checkbox? I think that should be checkbox.

**Comment by amitguptagwl** [comment]
button. even current check boxes need to be replaced with buttons. So more buttons can come in single line.

**Comment by ashishpatelcs** [comment]
@inikonorov Let me help you if there is any problem.

**Comment by amitguptagwl** [comment]
@ashishpatelcs The issue is not finished yet. We've to create a toolbar of buttons in place of checkboxes.

**Comment by ashishpatelcs** [comment]
Here are the screenshots. The page crashes as soon as the errors increases 400+ in the console. here's the error that gets repeated.
```
 Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonymous function)
	rejectPromise
	play
	onCharChange (shabdawali:148)
	typeText (shabdawali.js:232)
	(anonymous function) (shabdawali.js:250)
```

screenshots:
console errors-
![console](https://preview.ibb.co/jJSHU9/Screen_Shot_2018_09_25_at_5_53_55_PM.png)
crashes-
![crahes](https://preview.ibb.co/c7ft2U/Screen_Shot_2018_09_25_at_5_53_26_PM.png)

**Comment by ashishpatelcs** [comment]
@amitguptagwl Check out my PR #25
