### ISSUE TITLE
Demo: Provide an option to take text input

### ISSUE THREAD

**Issue by amitguptagwl** [amitguptagwl/shabdawali#21]
In the current [implementation](http://amitkumargupta.work/shabdawali/) text is hard coded. We want to give an option so that user can try the demo with different text. For this;

1. Add a button on the screen.
2. On click of that button, open a popup to take multiline text input.
3. restart the demo with new text.

**Comment by amitguptagwl** [comment]
Yes please.

> Please join the [Team](https://github.com/socialat/team) to support opensource projects
> Please [bookmark](https://github.com/amitguptagwl/shabdawali/stargazers) this project to support us

**Comment by asingh217** [comment]
Thanks, I will start working on this.

**Comment by msarfrazanwar** [comment]
> In the current [implementation](http://amitkumargupta.work/shabdawali/) text is hard coded. We want to give an option so that user can try the demo with different text. For this;
> 
> 1. Add a button on the screen.
> 2. On click of that button, open a popup to take multiline text input.
> 3. restart the demo with new text.

Hey , Can i also work on this ?

**Comment by amitguptagwl** [comment]
2 people together? No!! Let give some time to @asingh217 . If she doesn't finish it within a week or if there is no update then you can pick it. You can check more issues [here](https://github.com/socialat/team/issues/9)

> Please join the [Team](https://github.com/socialat/team) to support opensource projects
> Please [bookmark](https://github.com/amitguptagwl/shabdawali/stargazers) this project to support us

**Comment by ashishpatelcs** [comment]
@asingh217 Let me know if there is an issue. I can help you test from my end.

**Comment by asingh217** [comment]
> @asingh217 Let me know if there is an issue. I can help you test from my end.

Thanks @ashishpatelcs , I need some suggestion on UI items like the
1. Button Name 
2. Modal dialog Title
I have implemented the functional part. It will be helpful if you can review it and share your feedback.

Please let me know how to do i share my code. Should i share the commit page link here from my fork.

**Comment by amitguptagwl** [comment]
Here is your code changes: https://github.com/asingh217/shabdawali

**Comment by ashishpatelcs** [comment]
@asingh217 It would be better you can have it live on your GitHub pages so that I can see it working. Have you checked the code you've edited to work on your local machine? I have some doubts about it.

Let's make it work.

**Comment by amitguptagwl** [comment]
Here are the [common fonts](https://github.com/NaturalIntelligence/common-fonts) which are small in size and fulfill out need. Or you may simply use a button with text "edit text"

@ashishpatelcs You can check her changes here: http://htmlpreview.github.io/?https://github.com/asingh217/shabdawali/blob/master/index.html

**Comment by ashishpatelcs** [comment]
@amitguptagwl Thanks you.

@asingh217 You button and the modal box is working perfectly fine.

**Comment by asingh217** [comment]
Thanks,  I have updated the title and button name.
I will create a pull request.
