### ISSUE TITLE
A cascade of errors makes the UI crash

### ISSUE THREAD

**Issue by ashishpatelcs** [amitguptagwl/shabdawali#22]
while visiting http://amitkumargupta.work/shabdawali/ and checking the console of safari (mac OS), I see number of errors keep mounting and finally the website crashes and reloads. Please confirm the issue.

**Comment by amitguptagwl** [comment]
Unfortunately. I'm not having mac to confirm the issue. Can you please share the screenshot? or console logs?

**Comment by ashishpatelcs** [comment]
Here are the screenshots. The page crashes as soon as the errors increases 400+ in the console. here's the error that gets repeated.
```
 Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.
	(anonymous function)
	rejectPromise
	play
	onCharChange (shabdawali:148)
	typeText (shabdawali.js:232)
	(anonymous function) (shabdawali.js:250)
```

screenshots:
console errors-
![console](https://preview.ibb.co/jJSHU9/Screen_Shot_2018_09_25_at_5_53_55_PM.png)
crashes-
![crahes](https://preview.ibb.co/c7ft2U/Screen_Shot_2018_09_25_at_5_53_26_PM.png)

**Comment by ashishpatelcs** [comment]
If you can explain the context of this error. Maybe I can work on this with your help.

**Comment by amitguptagwl** [comment]
After googling a little bit I found this : https://forums.developer.apple.com/thread/94522

Hopefully, it can help you to solve this issue.

**Comment by ashishpatelcs** [comment]
Oh, that's the issue. Had to go to Safari -> Settings for this website -> Allow all auto-play. It worked and I could hear the tapping sound. No more console errors and crashes now.

But how can we ensure that a stable behavior for clients who have not enabled auto-play in their browsers? You basically have to do it for each website separately on safari.

**Comment by ashishpatelcs** [comment]
The console errors aren't there but the page is still crashing. Maybe we are calling this function to play audio too many times.

**Comment by amitguptagwl** [comment]
Yes, it is for key press sound effect in the demo. We can uncheck it by default to avoid this issue.

**Comment by ashishpatelcs** [comment]
The issue is fixed.
