### ISSUE TITLE
`dynamicPauseBeforeDelete` disabled by default.

### ISSUE THREAD

**Issue by SalchiPapa** [amitguptagwl/shabdawali#27]
@amitguptagwl currently there is no way of disabling `dynamicPauseBeforeDelete`, the next line will always enable it, even if the user explicitly passes `false` to this option:

* https://github.com/amitguptagwl/shabdawali/blob/master/src/shabdawali.js#L17

`this.dynamicPauseBeforeDelete = opts.dynamicPauseBeforeDelete || true;`

I also think it's better if the user has to explicitly enable this feature.

**Comment by SalchiPapa** [comment]
For non working example of `dynamicPauseBeforeDelete` explicitly being set to `false`, see:

* https://codepen.io/Ismael-VC/pen/bQLooV

**Comment by SalchiPapa** [comment]
@amitguptagwl thank you! Could you please tag a new release so this is reflected at npm?

**Comment by amitguptagwl** [comment]
oh yes. Sorry I missed.
