### ISSUE TITLE
Add long pause effect

### ISSUE THREAD

**Issue by amitguptagwl** [amitguptagwl/shabdawali#5]
User slowly reads long or complex words. We should give extra pause after such words. User may also want long pause effect after certain words.

Implementation Hint:

* When the current char is space (' ') extract the last word.
* check the length of word. If it is more than 5 letters then increase the interval before typing next word.

https://github.com/amitguptagwl/shabdawali/blob/master/riotjs/shabdawali.tag#L29

**Comment by Debojyoti-Chakraborty** [comment]
Hi, it's my first time contributing to GitHub.
Say, wouldn't it be better if we calculated the Interval based on the length of the word? 
So if the word is 16 letters long the pause will be double than if it is 8 letters long. The longer the word, the longer it will take the user to read.

**Comment by amitguptagwl** [comment]
Thanks @Debojyoti-Chakraborty for your PR. End result is awesome.

> Please [bookmark](https://github.com/amitguptagwl/shabdawali/stargazers) this project
