### ISSUE TITLE
Fix: jquery plugin gor multiple calls

### ISSUE THREAD

**Issue by amitguptagwl** [amitguptagwl/shabdawali#6]
jQuery plugin of shabdawali need to fixed when it is called multiple times on the same element. Check [demo.html](https://github.com/amitguptagwl/shabdawali/blob/master/jquery/demo.html) to experience the issue.

It works perfectly on page load. But when we want update the typing options then it's behavior is unexpected. Possible solution may be attach the options to tag itself and then read from their and don't apply the plugin if it is already bound.

https://github.com/amitguptagwl/shabdawali/tree/master/jquery

**Comment by ardyboy1** [comment]
I’ll take a crack at this if no one else has claimed it

**Comment by amitguptagwl** [comment]
@ardyboy1 yes please.

**Comment by amitguptagwl** [comment]
@ardyboy1 I've changed the implementation so this issue is not exist anymore. Thanks for your initiative
