### ISSUE TITLE
Add blinking cursor effects

### ISSUE THREAD

**Issue by amitguptagwl** [amitguptagwl/shabdawali#8]
Add blinking cursor effect. So user need not to add it by themselves. It should be added in such a way that it can be used to move cursor inside the text.

**Comment by ravikishorethella** [comment]
@amitguptagwl I'm interested working on this. Can you please guide me what to do?

**Comment by amitguptagwl** [comment]
there is a single js file to be modified so I believe, you should not face much problem

1. Add an option, so that user can decide if they want to add cursor effects.
2. use pipe sign for cursor effects '|'
3. use css to give blinking effects


there can be multiple approaches to add it, eg css after property, or js 'insertAdjacentElement', or something else. I believe the better approach should be appending 'span' with pipe sign after the target element and giving it css animation.

**Comment by ashishpatelcs** [comment]
Thank you for the friendly explanation. I'm working on it.

**Comment by amitguptagwl** [comment]
Thanks @ashishpatelcs to add blinking cursor effect to the demo.

**Comment by amitguptagwl** [comment]
@ravikishorethella @ashishpatelcs I've recently moved this effect to the library. Please have a look for learning purpose

**Comment by ashishpatelcs** [comment]
@amitguptagwl Thank you, I've seen it.

**Comment by ravikishorethella** [comment]
@amitguptagwl No. @ashishpatelcs said he's working on it
